### PR TITLE
Prepare for 0.5 Release

### LINKED ISSUE #213: Prepare 0.5 Release
This issue will result in the 0.5 release when merged. This is the first release since the project was moved from the nunit organization to my personal account.

### PR DESCRIPTION
**Pull request by CharliePoole**
Fixes #213

### CODE REVIEW

**Comment by immeraufdemhund** [comment]
I just saw that issue #211 was not mentioned in the release of 0.5... sad thing is who put it in and who reviewed ... Sorry about that.

**Comment by CharliePoole** [comment]
Too bad. I can fix online and for the next release. Issue for that PR was #75, which was not closed. I'll do that.

When you merge a PR, make sure the issue it fixed is closed, label it done and add to the next milestone. Listing done issues in the milestone is how I do the release notes.

**Comment by immeraufdemhund** [comment]
? Add to the next milestone? meaning if it wasn't already assigned a milestone? or if it was already marked as 0.5 i'd mark it to 0.6?

**Comment by CharliePoole** [comment]
Right. Because we never know who will have time to work on this, I don't generally assign most things to a milestone until they are done.

**Pull request merged**
